kind: pipeline
type: docker
name: netdevops cicd proof of concept

steps:
  - name: preping build
    image: vireakouk/netdevops-drone-nornir-scrapli:latest
    commands:
      - echo 'starting build'
      - git --version
      - python --version
      - pip list
      - git fetch
      - git checkout ${DRONE_BRANCH}
  
  - name: dry run
    image: vireakouk/netdevops-drone-nornir-scrapli:latest
    environment:
      NORNIR_USER:
        from_secret: NORNIR_USER
      NORNIR_SECRET:
        from_secret: NORNIR_SECRET
    commands:
      - git fetch
      - python deploy_baseconfig.py --dry_run
    when:
      branch:
        - dev
  
  - name: merge to main 
    image: vireakouk/netdevops-drone-nornir-scrapli:latest
    commands:
      - git checkout main
      - git branch -u origin/main
      - git merge dev
      - git remote -v
      - git push --all
      - git push --tags
    when:
      branch:
        - dev
        
  - name: deploy to production
    image: vireakouk/netdevops-drone-nornir-scrapli:latest
    environment:
      NORNIR_USER:
        from_secret: NORNIR_USER
      NORNIR_SECRET:
        from_secret: NORNIR_SECRET
    commands:
      - python deploy_baseconfig.py
    when:
      branch:
        - main

  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token: 
        from_secret: TELEGRAM_TOKEN
      to:
        from_secret: TELEGRAM_USER_ID
      # message: >
      #   {{#success build.status}}
      #     build {{build.number}} succeeded. Good job.
      #   {{else}}
      #     build {{build.number}} failed. Fix me please.
      #   {{/success}}
      message: >
        
        {{#success build.status}} ✔ {{ else }} :x: {{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }} * (type: `{{ build.event }}`)
        
        Commit: <http://192.168.0.200/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>

        Branch: <https://192.168.0.200/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>

        Author: {{ build.author }}      

        Build: <{{ build.link }}| Drone Build {{ build.number }} ↗ >
      
    when:
      status: [ success, failure ]
      branch: [ main, dev ]