ssh-keygen -f "/home/vireak/.ssh/known_hosts" -R "172.100.1.11"
ssh-keygen -f "/home/vireak/.ssh/known_hosts" -R "172.100.1.12"
ssh-keygen -f "/home/vireak/.ssh/known_hosts" -R "172.100.1.13"
ssh-keygen -f "/home/vireak/.ssh/known_hosts" -R "172.100.1.14"
ssh-keygen -f "/home/vireak/.ssh/known_hosts" -R "clab-eos-spine1"
ssh-keygen -f "/home/vireak/.ssh/known_hosts" -R "clab-eos-spine2"
ssh-keygen -f "/home/vireak/.ssh/known_hosts" -R "clab-eos-leaf1"
ssh-keygen -f "/home/vireak/.ssh/known_hosts" -R "clab-eos-leaf2"